version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  nginx:
    image: nginx:1.15.6
    ports:
      - '80:80'
    depends_on:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  db:
    image: mariadb:10.4.13
    environment:
      MYSQL_DATABASE: local_mirrev_com
      MYSQL_USER: user
      MYSQL_PASSWORD: passuser
      MYSQL_ROOT_PASSWORD: passroot
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: